// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineBookstore.Domain.Data;

#nullable disable

namespace OnlineBookstore.Migrations
{
    [DbContext(typeof(OnlineBookstoreContext))]
    [Migration("20260116100733_Seed100UniqueBooks")]
    partial class Seed100UniqueBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Data.OnlineBookstoreUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3781ad74-f56b-4599-92ed-dea6a3f30526",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2fa30603-04ef-4e75-9474-aeeed581703b",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOxcqjTNDXJLGGobJqkl7//1a48Jf31B5B+o9bLroDX0DByOVgrz5M/HNiRKJAO+pA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a8834ca8-1962-45c1-ad28-695e175c72c5",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        },
                        new
                        {
                            Id = "a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bc7b50b5-93ca-4e13-b9a4-f46aea3efd27",
                            Email = "sarah.tan@example.com",
                            EmailConfirmed = true,
                            FirstName = "Sarah",
                            LastName = "Tan",
                            LockoutEnabled = false,
                            NormalizedEmail = "SARAH.TAN@EXAMPLE.COM",
                            NormalizedUserName = "SARAH.TAN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPIBfW5ZyDeTT0CbfT0nJThJ8bgPixRJS7fIE2q5al7w8yJoa+VkunHQzOXTmESoig==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0e901433-3245-4e81-9a3e-22a9e08e644d",
                            TwoFactorEnabled = false,
                            UserName = "sarah.tan@example.com"
                        },
                        new
                        {
                            Id = "b2c3d4e5-f6a7-4b6c-9d0e-1f2a3b4c5d6e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fafb03ee-cefc-46c9-ae26-6f78c3339d0f",
                            Email = "muhammad.ali@example.com",
                            EmailConfirmed = true,
                            FirstName = "Muhammad",
                            LastName = "Ali",
                            LockoutEnabled = false,
                            NormalizedEmail = "MUHAMMAD.ALI@EXAMPLE.COM",
                            NormalizedUserName = "MUHAMMAD.ALI@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEWvaz/4RIW8YPhaMPnWIoTvHVdNbbpAS+awP3S2Y9MCNR+Wbf/DMFxGi3etqscTXA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "89b0ba5d-5342-40e1-a5f9-5f89425a6749",
                            TwoFactorEnabled = false,
                            UserName = "muhammad.ali@example.com"
                        },
                        new
                        {
                            Id = "c3d4e5f6-a7b8-4c7d-0e1f-2a3b4c5d6e7f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ca495769-ea4f-4d89-8ae3-e08360d622c5",
                            Email = "emily.wong@example.com",
                            EmailConfirmed = true,
                            FirstName = "Emily",
                            LastName = "Wong",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMILY.WONG@EXAMPLE.COM",
                            NormalizedUserName = "EMILY.WONG@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHDpnNj58tYt5PB0q35RGVwdqoOJB62+APuEvdzmOrJrAEv9NentawUwgdNx9sN5ZA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "971d7205-bfbd-4dad-a116-3494c175bad5",
                            TwoFactorEnabled = false,
                            UserName = "emily.wong@example.com"
                        },
                        new
                        {
                            Id = "d4e5f6a7-b8c9-4d8e-1f2a-3b4c5d6e7f8a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b77f1037-f0e6-44b6-80f1-9ed77a4b9ea0",
                            Email = "david.smith@example.com",
                            EmailConfirmed = true,
                            FirstName = "David",
                            LastName = "Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "DAVID.SMITH@EXAMPLE.COM",
                            NormalizedUserName = "DAVID.SMITH@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGyqv0WopzjvI+TaeeSbj4wRMQ1yEBUFmv2VY01vq5lOao5upS4/DY6iypImABpUig==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0e9626c4-5e1f-4575-90f2-e59c766b4217",
                            TwoFactorEnabled = false,
                            UserName = "david.smith@example.com"
                        },
                        new
                        {
                            Id = "e5f6a7b8-c9d0-4e9f-2a3b-4c5d6e7f8a9b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "39320557-b537-4c97-9f8b-b2a8503c9abc",
                            Email = "priya.sharma@example.com",
                            EmailConfirmed = true,
                            FirstName = "Priya",
                            LastName = "Sharma",
                            LockoutEnabled = false,
                            NormalizedEmail = "PRIYA.SHARMA@EXAMPLE.COM",
                            NormalizedUserName = "PRIYA.SHARMA@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFhVKRBJJbtUcZx/bvA/u/GQztY/TQXuHC6ddKa1h9N7w13Pb3KE/zbheEN4IqKsPA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e5875ef1-e087-45dd-9aeb-56fe582d3152",
                            TwoFactorEnabled = false,
                            UserName = "priya.sharma@example.com"
                        },
                        new
                        {
                            Id = "f6a7b8c9-d0e1-4fa0-3b4c-5d6e7f8a9b0c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "16ef0fda-5d60-4d10-87e3-e2e513e47718",
                            Email = "jason.lee@example.com",
                            EmailConfirmed = true,
                            FirstName = "Jason",
                            LastName = "Lee",
                            LockoutEnabled = false,
                            NormalizedEmail = "JASON.LEE@EXAMPLE.COM",
                            NormalizedUserName = "JASON.LEE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIVt5bAjN3jxajTqJ5qNMb+CGP7UXmm6HUJoYtnSyAgPC4kwYTP+SPUwJPDWouZB9A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3d84b75e-ab5c-46d2-83ef-3425154dd1be",
                            TwoFactorEnabled = false,
                            UserName = "jason.lee@example.com"
                        },
                        new
                        {
                            Id = "a7b8c9d0-e1f2-4fb1-4c5d-6e7f8a9b0c1d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dd5b61b2-52e6-476b-8795-b66785db27f0",
                            Email = "chloe.lim@example.com",
                            EmailConfirmed = true,
                            FirstName = "Chloe",
                            LastName = "Lim",
                            LockoutEnabled = false,
                            NormalizedEmail = "CHLOE.LIM@EXAMPLE.COM",
                            NormalizedUserName = "CHLOE.LIM@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBta5i/3D4YWk6w/TfgDXgeq2T2fQUeK4wWT1cG/IzKxv3jBg2Vw3WHKF9Vykep6XQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5df24e32-1530-41eb-8d4f-09d7e6c35943",
                            TwoFactorEnabled = false,
                            UserName = "chloe.lim@example.com"
                        },
                        new
                        {
                            Id = "b8c9d0e1-f2a3-4fc2-5d6e-7f8a9b0c1d2e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d664657d-1af0-4066-859c-c6bd5c0e5037",
                            Email = "ahmad.hassan@example.com",
                            EmailConfirmed = true,
                            FirstName = "Ahmad",
                            LastName = "Hassan",
                            LockoutEnabled = false,
                            NormalizedEmail = "AHMAD.HASSAN@EXAMPLE.COM",
                            NormalizedUserName = "AHMAD.HASSAN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFIlMYu64HHoewVeL1ECEQyoi2DD6sXhMWMUDBNjMzQGx9LoO/cfwg1iHe3aXN3WAg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0e1800aa-f8a9-4cc2-b5c0-a145c7842489",
                            TwoFactorEnabled = false,
                            UserName = "ahmad.hassan@example.com"
                        },
                        new
                        {
                            Id = "c9d0e1f2-a3b4-4fd3-6e7f-8a9b0c1d2e3f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0cd07925-cf79-4e76-865d-5245ce84116d",
                            Email = "linda.nguyen@example.com",
                            EmailConfirmed = true,
                            FirstName = "Linda",
                            LastName = "Nguyen",
                            LockoutEnabled = false,
                            NormalizedEmail = "LINDA.NGUYEN@EXAMPLE.COM",
                            NormalizedUserName = "LINDA.NGUYEN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ9rydH4oR1rspNxEJ/cAy/v6QKdnxlEd6s+0/mUz3umLavrPyE8UlyVfp1QsvCwBQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f259432d-5f75-473f-a0b0-80ec39db39c6",
                            TwoFactorEnabled = false,
                            UserName = "linda.nguyen@example.com"
                        },
                        new
                        {
                            Id = "d0e1f2a3-b4c5-4fe4-7f8a-9b0c1d2e3f4a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a62f35bb-6639-4ee5-bd7c-40876e2026f2",
                            Email = "robert.brown@example.com",
                            EmailConfirmed = true,
                            FirstName = "Robert",
                            LastName = "Brown",
                            LockoutEnabled = false,
                            NormalizedEmail = "ROBERT.BROWN@EXAMPLE.COM",
                            NormalizedUserName = "ROBERT.BROWN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBAjn4/dTGuEmpuMZXcAg/oODkkrrXbJg+17vk+aeHxrtWi23odrry4KNsJv4xp2Og==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "060867c4-e689-4e4a-a09a-164fbf541d75",
                            TwoFactorEnabled = false,
                            UserName = "robert.brown@example.com"
                        });
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PricePhysical")
                        .HasColumnType("float");

                    b.Property<double>("PriceSoftcopy")
                        .HasColumnType("float");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OnlineBookstore.Domain.Data.OnlineBookstoreUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OnlineBookstore.Domain.Data.OnlineBookstoreUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookstore.Domain.Data.OnlineBookstoreUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OnlineBookstore.Domain.Data.OnlineBookstoreUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Book", b =>
                {
                    b.HasOne("OnlineBookstore.Domain.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId");

                    b.HasOne("OnlineBookstore.Domain.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId");

                    b.HasOne("OnlineBookstore.Domain.Entities.Publisher", null)
                        .WithMany("Books")
                        .HasForeignKey("PublisherId");

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Order", b =>
                {
                    b.HasOne("OnlineBookstore.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("OnlineBookstore.Domain.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookstore.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Payment", b =>
                {
                    b.HasOne("OnlineBookstore.Domain.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("OnlineBookstore.Domain.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
