// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineBookstore.Domain.Data;

#nullable disable

namespace OnlineBookstore.Migrations
{
    [DbContext(typeof(OnlineBookstoreContext))]
    [Migration("20260116170507_FixedSeedWithGenres")]
    partial class FixedSeedWithGenres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Data.OnlineBookstoreUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3781ad74-f56b-4599-92ed-dea6a3f30526",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8c245f5a-94c6-4b04-8fe9-802dbb2a4f1d",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBt5YdHgA8hMMSjSDaUteBSsywmzmD6K8ZrE/xWGiLk2QOo8bdJi+atq0kbT2F6WUg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fef08faf-48ed-40c0-80c7-d92483553431",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        },
                        new
                        {
                            Id = "a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8bc28065-67ee-43fc-95b9-001207437728",
                            Email = "sarah.tan@example.com",
                            EmailConfirmed = true,
                            FirstName = "Sarah",
                            LastName = "Tan",
                            LockoutEnabled = false,
                            NormalizedEmail = "SARAH.TAN@EXAMPLE.COM",
                            NormalizedUserName = "SARAH.TAN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELan4KbKAI5BhPPvk1GHta2qJ9ujr5vwSEHRv1qsnjHhE/0p9YTzav4AvY9gzjkZuw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "84037725-c98d-47e0-87f2-140b8b2231b5",
                            TwoFactorEnabled = false,
                            UserName = "sarah.tan@example.com"
                        },
                        new
                        {
                            Id = "b2c3d4e5-f6a7-4b6c-9d0e-1f2a3b4c5d6e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "333206a4-c85c-4eda-b1e1-1766a285f0e6",
                            Email = "muhammad.ali@example.com",
                            EmailConfirmed = true,
                            FirstName = "Muhammad",
                            LastName = "Ali",
                            LockoutEnabled = false,
                            NormalizedEmail = "MUHAMMAD.ALI@EXAMPLE.COM",
                            NormalizedUserName = "MUHAMMAD.ALI@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENtK9xKb0ix1Ngv1c0+KC9Y+WFegJVHZRhA5jvk1prV8kQ+cqFzp3HbXlRSsUyDvIg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e246d8a3-634b-46f4-8aa6-c9fb79c6ea36",
                            TwoFactorEnabled = false,
                            UserName = "muhammad.ali@example.com"
                        },
                        new
                        {
                            Id = "c3d4e5f6-a7b8-4c7d-0e1f-2a3b4c5d6e7f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d2133d5d-db0b-4ae1-aa0e-4d85277c23a0",
                            Email = "emily.wong@example.com",
                            EmailConfirmed = true,
                            FirstName = "Emily",
                            LastName = "Wong",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMILY.WONG@EXAMPLE.COM",
                            NormalizedUserName = "EMILY.WONG@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGrf4CEWvXI6dHvTbB98lXvhYWuVI6KoaEVHM6+nBOGWvr2kYv3efQvXiC9xv59NfQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3aa1a3fb-954b-4865-a1e7-45148628ce6c",
                            TwoFactorEnabled = false,
                            UserName = "emily.wong@example.com"
                        },
                        new
                        {
                            Id = "d4e5f6a7-b8c9-4d8e-1f2a-3b4c5d6e7f8a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c7b981d8-7c8b-4f7c-8ca6-fe1826771800",
                            Email = "david.smith@example.com",
                            EmailConfirmed = true,
                            FirstName = "David",
                            LastName = "Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "DAVID.SMITH@EXAMPLE.COM",
                            NormalizedUserName = "DAVID.SMITH@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFnqIRD/YfttK9rUEocl1FFb4d8z/Q/hBOPohCf0XisWdQNnzrwoyr30LBCMkn+0cg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a8ab23d8-ef92-4315-800a-4f90b82f2166",
                            TwoFactorEnabled = false,
                            UserName = "david.smith@example.com"
                        },
                        new
                        {
                            Id = "e5f6a7b8-c9d0-4e9f-2a3b-4c5d6e7f8a9b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6b4eaee6-1a57-481b-9136-e0c3411da24b",
                            Email = "priya.sharma@example.com",
                            EmailConfirmed = true,
                            FirstName = "Priya",
                            LastName = "Sharma",
                            LockoutEnabled = false,
                            NormalizedEmail = "PRIYA.SHARMA@EXAMPLE.COM",
                            NormalizedUserName = "PRIYA.SHARMA@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECJfR4ZckVZWHg1zlPJPewLkmJ7jTWZV6HEhscxWSK439c+mcD4Kr/MV9ey7BeU03A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a0d50152-e18f-4c58-a40a-2b062666ebd3",
                            TwoFactorEnabled = false,
                            UserName = "priya.sharma@example.com"
                        },
                        new
                        {
                            Id = "f6a7b8c9-d0e1-4fa0-3b4c-5d6e7f8a9b0c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "541a251e-868b-45f6-bc9b-cfe7ffe00c9d",
                            Email = "jason.lee@example.com",
                            EmailConfirmed = true,
                            FirstName = "Jason",
                            LastName = "Lee",
                            LockoutEnabled = false,
                            NormalizedEmail = "JASON.LEE@EXAMPLE.COM",
                            NormalizedUserName = "JASON.LEE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENyyFffzeQ7DpnhHe/5wPgk2oNkhCnPzVigNAr5r7SzQps7APcRpyD/OQxIsrf9b2g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5f8737c2-0543-4a4a-89b5-183db5ed66b2",
                            TwoFactorEnabled = false,
                            UserName = "jason.lee@example.com"
                        },
                        new
                        {
                            Id = "a7b8c9d0-e1f2-4fb1-4c5d-6e7f8a9b0c1d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5cd889bd-08a6-43ab-a130-8579cc26ce99",
                            Email = "chloe.lim@example.com",
                            EmailConfirmed = true,
                            FirstName = "Chloe",
                            LastName = "Lim",
                            LockoutEnabled = false,
                            NormalizedEmail = "CHLOE.LIM@EXAMPLE.COM",
                            NormalizedUserName = "CHLOE.LIM@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEjxGCyv6n1IxlhCAcaan0H4rmRo8qkG0zlX6xSBz0SgPKvZOnIUGUVNjr+297jKlg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7bd95c1c-8390-4055-9674-0c3ba529e1d3",
                            TwoFactorEnabled = false,
                            UserName = "chloe.lim@example.com"
                        },
                        new
                        {
                            Id = "b8c9d0e1-f2a3-4fc2-5d6e-7f8a9b0c1d2e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3eaa844d-4a0e-4ea6-b366-9b1740e591b6",
                            Email = "ahmad.hassan@example.com",
                            EmailConfirmed = true,
                            FirstName = "Ahmad",
                            LastName = "Hassan",
                            LockoutEnabled = false,
                            NormalizedEmail = "AHMAD.HASSAN@EXAMPLE.COM",
                            NormalizedUserName = "AHMAD.HASSAN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHbnb6OZL+o5bDlq/sj7MLer1o0b9eov1n9u8fge1LQkbG/OjmkYRoy0PvR82PhVUQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2b2614bb-9282-4b5b-bbe3-e07a5f0ce2ae",
                            TwoFactorEnabled = false,
                            UserName = "ahmad.hassan@example.com"
                        },
                        new
                        {
                            Id = "c9d0e1f2-a3b4-4fd3-6e7f-8a9b0c1d2e3f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7901234a-1ce0-4bdc-a79a-1a5f98bebbdd",
                            Email = "linda.nguyen@example.com",
                            EmailConfirmed = true,
                            FirstName = "Linda",
                            LastName = "Nguyen",
                            LockoutEnabled = false,
                            NormalizedEmail = "LINDA.NGUYEN@EXAMPLE.COM",
                            NormalizedUserName = "LINDA.NGUYEN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECnpvd8E37QiKxHJ1UGMFlyeGmuw52e9l7azqfeOubVwBsML9uebTDThXS5yLXTvag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c705b852-c8b3-45ad-b8b6-afb44fd6ccf7",
                            TwoFactorEnabled = false,
                            UserName = "linda.nguyen@example.com"
                        },
                        new
                        {
                            Id = "d0e1f2a3-b4c5-4fe4-7f8a-9b0c1d2e3f4a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "32455635-0a6b-4b53-9cf7-b21d5b4793d7",
                            Email = "robert.brown@example.com",
                            EmailConfirmed = true,
                            FirstName = "Robert",
                            LastName = "Brown",
                            LockoutEnabled = false,
                            NormalizedEmail = "ROBERT.BROWN@EXAMPLE.COM",
                            NormalizedUserName = "ROBERT.BROWN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGrSqlP4lEtBytIr5LdyC456keoOEESP9BG0yL8Wr5gnuVzGCYerZAvheQYiaxTJrQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "673ed6e2-4240-4d45-9840-3dfa505dcaea",
                            TwoFactorEnabled = false,
                            UserName = "robert.brown@example.com"
                        });
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PricePhysical")
                        .HasColumnType("float");

                    b.Property<double>("PriceSoftcopy")
                        .HasColumnType("float");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 1,
                            ISBN = "9780743273565",
                            ImageLink = "https://m.media-amazon.com/images/I/71FTb9X6wsL.jpg",
                            PricePhysical = 15.99,
                            PriceSoftcopy = 9.9900000000000002,
                            StockQuantity = 50,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 1,
                            ISBN = "9780061120084",
                            ImageLink = "https://m.media-amazon.com/images/I/81gepf1eMqL.jpg",
                            PricePhysical = 12.5,
                            PriceSoftcopy = 7.9900000000000002,
                            StockQuantity = 35,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 2,
                            ISBN = "9780451524935",
                            ImageLink = "https://m.media-amazon.com/images/I/71kxa1-qmfL.jpg",
                            PricePhysical = 10.0,
                            PriceSoftcopy = 5.9900000000000002,
                            StockQuantity = 100,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 1,
                            ISBN = "9780141439518",
                            ImageLink = "https://m.media-amazon.com/images/I/71Q1Iu4suAL.jpg",
                            PricePhysical = 9.9900000000000002,
                            PriceSoftcopy = 4.9900000000000002,
                            StockQuantity = 60,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 1,
                            ISBN = "9780316769488",
                            ImageLink = "https://m.media-amazon.com/images/I/8125BD7z9pL.jpg",
                            PricePhysical = 14.0,
                            PriceSoftcopy = 8.5,
                            StockQuantity = 40,
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 1,
                            ISBN = "9780141439556",
                            ImageLink = "https://m.media-amazon.com/images/I/81Y7p99uRHL.jpg",
                            PricePhysical = 11.0,
                            PriceSoftcopy = 5.0,
                            StockQuantity = 20,
                            Title = "Wuthering Heights"
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 1,
                            ISBN = "9780142437247",
                            ImageLink = "https://m.media-amazon.com/images/I/71d5f-9Y6uL.jpg",
                            PricePhysical = 18.0,
                            PriceSoftcopy = 9.0,
                            StockQuantity = 15,
                            Title = "Moby Dick"
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 1,
                            ISBN = "9780140268867",
                            ImageLink = "https://m.media-amazon.com/images/I/81mE79Y+v9L.jpg",
                            PricePhysical = 16.0,
                            PriceSoftcopy = 8.0,
                            StockQuantity = 30,
                            Title = "The Odyssey"
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 1,
                            ISBN = "9780143107637",
                            ImageLink = "https://m.media-amazon.com/images/I/71O2XI6Df6L.jpg",
                            PricePhysical = 17.5,
                            PriceSoftcopy = 10.0,
                            StockQuantity = 25,
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 2,
                            ISBN = "9780060850524",
                            ImageLink = "https://m.media-amazon.com/images/I/81mXqW2H6sL.jpg",
                            PricePhysical = 13.99,
                            PriceSoftcopy = 7.9900000000000002,
                            StockQuantity = 45,
                            Title = "Brave New World"
                        },
                        new
                        {
                            Id = 11,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 3,
                            ISBN = "9780547928227",
                            ImageLink = "https://m.media-amazon.com/images/I/710+HcoPgtL.jpg",
                            PricePhysical = 25.0,
                            PriceSoftcopy = 15.0,
                            StockQuantity = 20,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 12,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 2,
                            ISBN = "9780441172719",
                            ImageLink = "https://m.media-amazon.com/images/I/818pgeS7YdL.jpg",
                            PricePhysical = 22.0,
                            PriceSoftcopy = 12.0,
                            StockQuantity = 45,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 13,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 2,
                            ISBN = "9780553293357",
                            ImageLink = "https://m.media-amazon.com/images/I/71UupBy6S7L.jpg",
                            PricePhysical = 18.5,
                            PriceSoftcopy = 10.0,
                            StockQuantity = 30,
                            Title = "Foundation"
                        },
                        new
                        {
                            Id = 14,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 2,
                            ISBN = "9780441569595",
                            ImageLink = "https://m.media-amazon.com/images/I/91BpM6vI69L.jpg",
                            PricePhysical = 16.0,
                            PriceSoftcopy = 9.0,
                            StockQuantity = 25,
                            Title = "Neuromancer"
                        },
                        new
                        {
                            Id = 15,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 2,
                            ISBN = "9780553283686",
                            ImageLink = "https://m.media-amazon.com/images/I/91XmB0vG-EL.jpg",
                            PricePhysical = 19.0,
                            PriceSoftcopy = 11.0,
                            StockQuantity = 12,
                            Title = "Hyperion"
                        },
                        new
                        {
                            Id = 16,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 2,
                            ISBN = "9780553418026",
                            ImageLink = "https://m.media-amazon.com/images/I/81vSXYYmXfL.jpg",
                            PricePhysical = 15.0,
                            PriceSoftcopy = 8.0,
                            StockQuantity = 55,
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = 17,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 2,
                            ISBN = "9780593135204",
                            ImageLink = "https://m.media-amazon.com/images/I/919YpC-N8rL.jpg",
                            PricePhysical = 28.0,
                            PriceSoftcopy = 14.0,
                            StockQuantity = 60,
                            Title = "Project Hail Mary"
                        },
                        new
                        {
                            Id = 18,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 3,
                            ISBN = "9780380789030",
                            ImageLink = "https://m.media-amazon.com/images/I/91nKzUoR9LL.jpg",
                            PricePhysical = 16.5,
                            PriceSoftcopy = 9.5,
                            StockQuantity = 30,
                            Title = "American Gods"
                        },
                        new
                        {
                            Id = 19,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 3,
                            ISBN = "9780765365279",
                            ImageLink = "https://m.media-amazon.com/images/I/91I06L1T2eL.jpg",
                            PricePhysical = 35.0,
                            PriceSoftcopy = 20.0,
                            StockQuantity = 15,
                            Title = "The Way of Kings"
                        },
                        new
                        {
                            Id = 20,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 3,
                            ISBN = "9780765350381",
                            ImageLink = "https://m.media-amazon.com/images/I/91U676J9OqL.jpg",
                            PricePhysical = 24.0,
                            PriceSoftcopy = 12.0,
                            StockQuantity = 40,
                            Title = "Mistborn"
                        },
                        new
                        {
                            Id = 21,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 4,
                            ISBN = "9780735211292",
                            ImageLink = "https://m.media-amazon.com/images/I/91bYsX41DVL.jpg",
                            PricePhysical = 18.0,
                            PriceSoftcopy = 12.0,
                            StockQuantity = 150,
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            Id = 22,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 4,
                            ISBN = "9781455586691",
                            ImageLink = "https://m.media-amazon.com/images/I/417S9k6O6DL.jpg",
                            PricePhysical = 17.0,
                            PriceSoftcopy = 9.0,
                            StockQuantity = 55,
                            Title = "Deep Work"
                        },
                        new
                        {
                            Id = 23,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 5,
                            ISBN = "9780062316097",
                            ImageLink = "https://m.media-amazon.com/images/I/713jIoMO3UL.jpg",
                            PricePhysical = 24.989999999999998,
                            PriceSoftcopy = 14.99,
                            StockQuantity = 70,
                            Title = "Sapiens"
                        },
                        new
                        {
                            Id = 24,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 4,
                            ISBN = "9780804139298",
                            ImageLink = "https://m.media-amazon.com/images/I/71m-9S36SGL.jpg",
                            PricePhysical = 21.0,
                            PriceSoftcopy = 11.0,
                            StockQuantity = 80,
                            Title = "Zero to One"
                        },
                        new
                        {
                            Id = 25,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 4,
                            ISBN = "9780307887894",
                            ImageLink = "https://m.media-amazon.com/images/I/81-QB7nDh4L.jpg",
                            PricePhysical = 25.0,
                            PriceSoftcopy = 15.0,
                            StockQuantity = 50,
                            Title = "The Lean Startup"
                        },
                        new
                        {
                            Id = 26,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 4,
                            ISBN = "9781612680194",
                            ImageLink = "https://m.media-amazon.com/images/I/81bsw6fnUiL.jpg",
                            PricePhysical = 14.0,
                            PriceSoftcopy = 7.0,
                            StockQuantity = 200,
                            Title = "Rich Dad Poor Dad"
                        },
                        new
                        {
                            Id = 27,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 4,
                            ISBN = "9780857197689",
                            ImageLink = "https://m.media-amazon.com/images/I/81Lb75rMSdL.jpg",
                            PricePhysical = 19.5,
                            PriceSoftcopy = 10.0,
                            StockQuantity = 100,
                            Title = "The Psychology of Money"
                        },
                        new
                        {
                            Id = 28,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 4,
                            ISBN = "9780307465351",
                            ImageLink = "https://m.media-amazon.com/images/I/81qW97nxuNL.jpg",
                            PricePhysical = 22.0,
                            PriceSoftcopy = 11.0,
                            StockQuantity = 40,
                            Title = "The 4-Hour Workweek"
                        },
                        new
                        {
                            Id = 29,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 5,
                            ISBN = "9781501135910",
                            ImageLink = "https://m.media-amazon.com/images/I/8166D8+7SXL.jpg",
                            PricePhysical = 18.0,
                            PriceSoftcopy = 9.0,
                            StockQuantity = 65,
                            Title = "Shoe Dog"
                        },
                        new
                        {
                            Id = 30,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 4,
                            ISBN = "9780061241895",
                            ImageLink = "https://m.media-amazon.com/images/I/81vYkY9P69L.jpg",
                            PricePhysical = 17.0,
                            PriceSoftcopy = 8.5,
                            StockQuantity = 35,
                            Title = "Influence"
                        },
                        new
                        {
                            Id = 31,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 6,
                            ISBN = "9781250301697",
                            ImageLink = "https://m.media-amazon.com/images/I/81JJ7fyyKyL.jpg",
                            PricePhysical = 19.989999999999998,
                            PriceSoftcopy = 11.0,
                            StockQuantity = 110,
                            Title = "The Silent Patient"
                        },
                        new
                        {
                            Id = 32,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 1,
                            ISBN = "9780735219090",
                            ImageLink = "https://m.media-amazon.com/images/I/81O1oy0y9eL.jpg",
                            PricePhysical = 15.0,
                            PriceSoftcopy = 8.5,
                            StockQuantity = 90,
                            Title = "Where the Crawdads Sing"
                        },
                        new
                        {
                            Id = 33,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 1,
                            ISBN = "9780062315007",
                            ImageLink = "https://m.media-amazon.com/images/I/51Z906VNo9L.jpg",
                            PricePhysical = 14.0,
                            PriceSoftcopy = 7.0,
                            StockQuantity = 150,
                            Title = "The Alchemist"
                        },
                        new
                        {
                            Id = 34,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 1,
                            ISBN = "9780345803788",
                            ImageLink = "https://m.media-amazon.com/images/I/81WojU7Y7-L.jpg",
                            PricePhysical = 16.0,
                            PriceSoftcopy = 9.0,
                            StockQuantity = 80,
                            Title = "Crazy Rich Asians"
                        },
                        new
                        {
                            Id = 35,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 5,
                            ISBN = "9781590302255",
                            ImageLink = "https://m.media-amazon.com/images/I/712K4PankpL.jpg",
                            PricePhysical = 10.0,
                            PriceSoftcopy = 4.0,
                            StockQuantity = 200,
                            Title = "The Art of War"
                        },
                        new
                        {
                            Id = 36,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 4,
                            ISBN = "9780374533557",
                            ImageLink = "https://m.media-amazon.com/images/I/71f66SAnS9L.jpg",
                            PricePhysical = 20.0,
                            PriceSoftcopy = 10.0,
                            StockQuantity = 40,
                            Title = "Thinking, Fast and Slow"
                        },
                        new
                        {
                            Id = 37,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 5,
                            ISBN = "9780399590504",
                            ImageLink = "https://m.media-amazon.com/images/I/81WojU7Y7-L.jpg",
                            PricePhysical = 18.0,
                            PriceSoftcopy = 9.0,
                            StockQuantity = 75,
                            Title = "Educated"
                        },
                        new
                        {
                            Id = 38,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 5,
                            ISBN = "9781524763138",
                            ImageLink = "https://m.media-amazon.com/images/I/81h2gWcq95L.jpg",
                            PricePhysical = 25.0,
                            PriceSoftcopy = 12.5,
                            StockQuantity = 60,
                            Title = "Becoming"
                        },
                        new
                        {
                            Id = 39,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 4,
                            ISBN = "9781982137274",
                            ImageLink = "https://m.media-amazon.com/images/I/71YV6Xo7+vL.jpg",
                            PricePhysical = 16.0,
                            PriceSoftcopy = 8.0,
                            StockQuantity = 100,
                            Title = "The 7 Habits"
                        },
                        new
                        {
                            Id = 40,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 1,
                            ISBN = "9780312330538",
                            ImageLink = "https://m.media-amazon.com/images/I/91M-vG6K8SL.jpg",
                            PricePhysical = 22.0,
                            PriceSoftcopy = 11.0,
                            StockQuantity = 30,
                            Title = "Shantaram"
                        });
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dystopian"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Self-Help"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Thriller"
                        });
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OnlineBookstore.Domain.Data.OnlineBookstoreUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OnlineBookstore.Domain.Data.OnlineBookstoreUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookstore.Domain.Data.OnlineBookstoreUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OnlineBookstore.Domain.Data.OnlineBookstoreUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Book", b =>
                {
                    b.HasOne("OnlineBookstore.Domain.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId");

                    b.HasOne("OnlineBookstore.Domain.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId");

                    b.HasOne("OnlineBookstore.Domain.Entities.Publisher", null)
                        .WithMany("Books")
                        .HasForeignKey("PublisherId");

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Order", b =>
                {
                    b.HasOne("OnlineBookstore.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("OnlineBookstore.Domain.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookstore.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Payment", b =>
                {
                    b.HasOne("OnlineBookstore.Domain.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("OnlineBookstore.Domain.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
