// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineBookstore.Domain.Data;

#nullable disable

namespace OnlineBookstore.Migrations
{
    [DbContext(typeof(OnlineBookstoreContext))]
    [Migration("20260116100143_SeedMoreUsers")]
    partial class SeedMoreUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Data.OnlineBookstoreUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3781ad74-f56b-4599-92ed-dea6a3f30526",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1d9bcc1e-7b64-4b8a-bce6-c6d924610c63",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELXybFrNs5B1zZNzHOF6yUgFU4NXU9cQMzFh4aELz0AU+/bXcvc9qmxB0wsxIJbMEg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "765a0e52-a866-4d7e-8528-a3cc74886c66",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        },
                        new
                        {
                            Id = "a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "30e07781-99c0-43eb-bbf7-cb74c089792c",
                            Email = "sarah.tan@example.com",
                            EmailConfirmed = true,
                            FirstName = "Sarah",
                            LastName = "Tan",
                            LockoutEnabled = false,
                            NormalizedEmail = "SARAH.TAN@EXAMPLE.COM",
                            NormalizedUserName = "SARAH.TAN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEK6Tg9krOgM9A/m1vh7QJ9qA7gb+XuUsbpXCLF+9kFA8M27xiIXYk5026w8lMZVQ5A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7e759eb2-9d01-4262-84a0-6cb47bf67827",
                            TwoFactorEnabled = false,
                            UserName = "sarah.tan@example.com"
                        },
                        new
                        {
                            Id = "b2c3d4e5-f6a7-4b6c-9d0e-1f2a3b4c5d6e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9f1890a9-55bc-49cd-8560-4473eb62f54c",
                            Email = "muhammad.ali@example.com",
                            EmailConfirmed = true,
                            FirstName = "Muhammad",
                            LastName = "Ali",
                            LockoutEnabled = false,
                            NormalizedEmail = "MUHAMMAD.ALI@EXAMPLE.COM",
                            NormalizedUserName = "MUHAMMAD.ALI@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEL2tkMrhFZMO4BaqPd1HjcXK3M3/Xtn4Os50hZeIuPCR5/I8pmlZIZQCnuq6RjsJWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9bbe8d02-a051-47fd-b43a-113c79c29bf0",
                            TwoFactorEnabled = false,
                            UserName = "muhammad.ali@example.com"
                        },
                        new
                        {
                            Id = "c3d4e5f6-a7b8-4c7d-0e1f-2a3b4c5d6e7f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "835c0e75-9f33-48ef-b6d5-f090c33f46f0",
                            Email = "emily.wong@example.com",
                            EmailConfirmed = true,
                            FirstName = "Emily",
                            LastName = "Wong",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMILY.WONG@EXAMPLE.COM",
                            NormalizedUserName = "EMILY.WONG@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBuT44OiWPMP8v6vOLOWisSBCeMq3eBoWqz+O1lq6zho+niOJTLhUVzhxGG6q0sYMg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d10cbe82-56ae-4bbb-af7a-a6c6e7336e1d",
                            TwoFactorEnabled = false,
                            UserName = "emily.wong@example.com"
                        },
                        new
                        {
                            Id = "d4e5f6a7-b8c9-4d8e-1f2a-3b4c5d6e7f8a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "849b1ae1-e3f8-4e62-aeb0-4b645b21ddb2",
                            Email = "david.smith@example.com",
                            EmailConfirmed = true,
                            FirstName = "David",
                            LastName = "Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "DAVID.SMITH@EXAMPLE.COM",
                            NormalizedUserName = "DAVID.SMITH@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEL3/lIA6FEAXSjP5y+9sPXAu0tTLcIYKBxdKFUGSsbvCUOBcniHiNi9lQVoOtQUn8w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e361fb8e-4458-4c46-a3ec-21bd8222cc3a",
                            TwoFactorEnabled = false,
                            UserName = "david.smith@example.com"
                        },
                        new
                        {
                            Id = "e5f6a7b8-c9d0-4e9f-2a3b-4c5d6e7f8a9b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c03da8c8-2d5d-4bcc-8620-b0eadd0820ab",
                            Email = "priya.sharma@example.com",
                            EmailConfirmed = true,
                            FirstName = "Priya",
                            LastName = "Sharma",
                            LockoutEnabled = false,
                            NormalizedEmail = "PRIYA.SHARMA@EXAMPLE.COM",
                            NormalizedUserName = "PRIYA.SHARMA@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEI8Ow7VSWjubi5Ty2LlCBNuIekSRpA0AZ6vvNj3mHx4oZC5b3R00IKnEpIiLbmjsew==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "54af65f1-03d8-4cba-857e-0df37abc927c",
                            TwoFactorEnabled = false,
                            UserName = "priya.sharma@example.com"
                        },
                        new
                        {
                            Id = "f6a7b8c9-d0e1-4fa0-3b4c-5d6e7f8a9b0c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ee5c124a-5570-4c1a-ad93-f3df37dc11e8",
                            Email = "jason.lee@example.com",
                            EmailConfirmed = true,
                            FirstName = "Jason",
                            LastName = "Lee",
                            LockoutEnabled = false,
                            NormalizedEmail = "JASON.LEE@EXAMPLE.COM",
                            NormalizedUserName = "JASON.LEE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFqIYDaJHKrwFywgpklKTXu93N/G5ANEUWHVifI3Gv6gWkQdCr+dIpPEtFpgJJbwhw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3368a3c1-cfcc-46d2-9dea-ebea25a71fb8",
                            TwoFactorEnabled = false,
                            UserName = "jason.lee@example.com"
                        },
                        new
                        {
                            Id = "a7b8c9d0-e1f2-4fb1-4c5d-6e7f8a9b0c1d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "11eab70c-5764-4e88-817a-48a9e5a6ee0b",
                            Email = "chloe.lim@example.com",
                            EmailConfirmed = true,
                            FirstName = "Chloe",
                            LastName = "Lim",
                            LockoutEnabled = false,
                            NormalizedEmail = "CHLOE.LIM@EXAMPLE.COM",
                            NormalizedUserName = "CHLOE.LIM@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJP9vZHfRn2e0klhdkqmPHrdLvXnOdsZWbS8hH2wxM4Qp1V1ZurFjmtCwZrIgOUGlA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b00222b3-6a97-47b0-8f75-33d057c06dd0",
                            TwoFactorEnabled = false,
                            UserName = "chloe.lim@example.com"
                        },
                        new
                        {
                            Id = "b8c9d0e1-f2a3-4fc2-5d6e-7f8a9b0c1d2e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1f4170ba-bfaa-48e1-b9d9-67d98484eb58",
                            Email = "ahmad.hassan@example.com",
                            EmailConfirmed = true,
                            FirstName = "Ahmad",
                            LastName = "Hassan",
                            LockoutEnabled = false,
                            NormalizedEmail = "AHMAD.HASSAN@EXAMPLE.COM",
                            NormalizedUserName = "AHMAD.HASSAN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAf/rbdYR4d9E9qETgTBw6Dk118U28dZi5mggYrdYQkrv/V+O/0Ln2e3zl/wZ/fV1g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6c498aba-e336-475c-a0f7-516e403396e8",
                            TwoFactorEnabled = false,
                            UserName = "ahmad.hassan@example.com"
                        },
                        new
                        {
                            Id = "c9d0e1f2-a3b4-4fd3-6e7f-8a9b0c1d2e3f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "084a5b53-0297-4fff-bc0d-f59bfa1617bc",
                            Email = "linda.nguyen@example.com",
                            EmailConfirmed = true,
                            FirstName = "Linda",
                            LastName = "Nguyen",
                            LockoutEnabled = false,
                            NormalizedEmail = "LINDA.NGUYEN@EXAMPLE.COM",
                            NormalizedUserName = "LINDA.NGUYEN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGR7C9CZ9rElqXmbyHraj9bcfNQhJU89abrRmmU0+X5KIevBMkALUeKXkS/jj8OlEg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "beefba47-edac-4ee9-9330-376412f5c803",
                            TwoFactorEnabled = false,
                            UserName = "linda.nguyen@example.com"
                        },
                        new
                        {
                            Id = "d0e1f2a3-b4c5-4fe4-7f8a-9b0c1d2e3f4a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "501b4bb5-0495-4af5-8d42-f1154c9c2cc8",
                            Email = "robert.brown@example.com",
                            EmailConfirmed = true,
                            FirstName = "Robert",
                            LastName = "Brown",
                            LockoutEnabled = false,
                            NormalizedEmail = "ROBERT.BROWN@EXAMPLE.COM",
                            NormalizedUserName = "ROBERT.BROWN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECqqCaEFbjIwCfbeij6puls/0acJunpziPL3t1xcQleSksnUtl0Lqg6z/x4rLLnrug==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eb554e52-7733-4c04-a822-bd10823cd8c8",
                            TwoFactorEnabled = false,
                            UserName = "robert.brown@example.com"
                        });
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PricePhysical")
                        .HasColumnType("float");

                    b.Property<double>("PriceSoftcopy")
                        .HasColumnType("float");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OnlineBookstore.Domain.Data.OnlineBookstoreUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OnlineBookstore.Domain.Data.OnlineBookstoreUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookstore.Domain.Data.OnlineBookstoreUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OnlineBookstore.Domain.Data.OnlineBookstoreUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Book", b =>
                {
                    b.HasOne("OnlineBookstore.Domain.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId");

                    b.HasOne("OnlineBookstore.Domain.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId");

                    b.HasOne("OnlineBookstore.Domain.Entities.Publisher", null)
                        .WithMany("Books")
                        .HasForeignKey("PublisherId");

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Order", b =>
                {
                    b.HasOne("OnlineBookstore.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("OnlineBookstore.Domain.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookstore.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Payment", b =>
                {
                    b.HasOne("OnlineBookstore.Domain.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("OnlineBookstore.Domain.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("OnlineBookstore.Domain.Entities.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
